on: [workflow_dispatch]
name: Azure Infrastructure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: grom88
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/config.json
          failOnStdErr: false

      # - name: deploy
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: grom88T
      #     template: ./infrastructure/main.bicep
      #     parameters: environment=test resourcePostfix=grom88T
      #     failOnStdErr: false